// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmeswqiiplghopwlyhfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZXN3cWlpcGxnaG9wd2x5aGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjEyNDMsImV4cCI6MjA2NjI5NzI0M30.lOtFA3J7Lnz4GVvlIu4LTloXRXWfkUQAfwB0FQs5JXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);